# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33763a0acbb2f6d1df4d8b4f3eb5214e488c76e090994cc611bc38eed05ab1fba05f526154f02c48b3d2c60373fa47de992928bcec7f20e9fb8ed3ed27b299b6

test:
  secret_key_base: 242b62cb6e21788d14ecc1de16a93649df51e4df94406a985e2d1b8727cc9270aa8d23a893c5f2efdb49c79dbcaf0a3da5ff08d59c5ce8d1847cf9396a74963f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
